version: 0.2

phases:
#  install:
#    commands:
#      # Install any required dependencies here
  build:
    commands:
      - pwd
      - ls -l
      - chmod +x sample_file.sh
      - sample_file.sh  # Execute the script to generate sample_file.txt

artifacts:
  files:
    - sample_file.txt  # Specify correct path if needed