version: 0.2

phases:
#  install:
#    commands:
#      # Install any required dependencies here
  build:
    commands:
      - pwd
      - ls -l
      - chmod +x shell-files/upload-to-s3.sh
      - shell-files/upload-to-s3.sh  # Execute the script to generate sample_file.txt

artifacts:
  files:
    - shell-files/sample_file.txt  # Specify correct path if needed