#Description: Basic EC2 instance
#
#Resources:
#  MyEC2Instance:
#    Type: AWS::EC2::Instance
#    Properties:
#      AvailabilityZone: us-east-1a
#      ImageId: ami-0c7217cdde317cfec
#      InstanceType: t2.micro
#      SecurityGroups:
#        - default
#        - !Ref SSHSecurityGroup
#
#  SSHSecurityGroup:
#    Type: AWS::EC2::SecurityGroup
#    Properties:
#      GroupDescription: my new SSH grp
#      SecurityGroupIngress:
#        - IpProtocol: tcp
#          FromPort: 22
#          ToPort: 22
#          CidrIp: 0.0.0.0/0


AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an EC2 instance with a security group
Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: My security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0   # Allow SSH access from anywhere
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      AvailabilityZone: us-east-1a
      ImageId: ami-0c7217cdde317cfec
      SecurityGroups:
        - Ref: MySecurityGroup
